package com.prasannjeet.battleship.model;

import lombok.Data;

import javax.persistence.Id;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;

/**
 * @author Prasannjeet <strong>Description: </strong>
 * A simple POJO class that represents the <b>GameInstance</b> model in a simpler format that can be sent to the client.
 * This is used to draw the boards in the client side.
 */
@Data
public class GameModel {

    /**
     * The user id generated by the controller. This is not the unique key.
     */
    String userId;

    /**
     * The username of the player. Entered by the player in the client side. Is the unique key.
     */
    @Id String userName;

    /**
     * The unique id used to communicate with the server via web-sockets. This id is common for both player one and
     * player two in a game. It is saved as a primary key in Player Matches model.
     */
    String socketUrl;

    /**
     * Coordinates where enemy has attacked.
     */
    List<Integer> attackedByEnemyCoordinates;

    /**
     * Coordinates where the player has attacked the enemy.
     */
    HashMap<Integer, Boolean> attackedCoordinates;

    /**
     * Ship coordinates of ships in a board.
     */
    HashMap<Ship.ShipNameList, int[]> shipPositions;

    /**
     * Boolean variable indicating if the player has won the game or not.
     */
    boolean won;

    /**
     * Simple constructor populating this class. The conversion happens in the logic package.
     * @param userId User id of the user.
     * @param userName User name of the user.
     */
    public GameModel(String userId, String userName) {
        this.userId = userId;
        this.userName = userName;
        attackedByEnemyCoordinates = new ArrayList<>();
        attackedCoordinates = new HashMap<>();
        shipPositions = new HashMap<>();
        this.won = false;
    }
}
