//currently not used
package com.prasannjeet.battleship.model;

import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.data.annotation.Id;

/**
 * @author Prasannjeet <strong>Description: </strong>
 * Model that persists in MongoDB. Contains the user id's of both players currently playing the game and the primary
 * key, which is the socket id used by both the blayers to communicate with the server. The entry should be deleted
 * after the game finished. Will be updated in next versions. //TODO
 */
@Data
@NoArgsConstructor
public class PlayerMatches {

    /**
     * The unique id, which also is the web socket address used to communicate with the server by the players.
     */
    @Id String webSocketAddress;

    /**
     * The user id of player 1.
     */
    private String player1;

    /**
     * The user id of player 2.
     */
    private String player2;

    /**
     * A basic constructor that populates the model. The socket id is autogenerated by MongoDB.
     * @param player1 The id of player 1.
     * @param player2 The id of player 2.
     */
    public PlayerMatches(String player1, String player2) {
        this.player1 = player1;
        this.player2 = player2;
    }

    /**
     * A constructor that only populates the socket id and the user id of player one. The model is instantiated
     * initially from this constructor and is later populated with the player 2 id from the previous constructor.
     * @param player1 The id of player 1.
     */
    public PlayerMatches(String player1) {
        this.player1 = player1;
    }
}
